version: '3.8'

services:
  api:
    image: api:prod
    container_name: api
    depends_on:
      - db
    build:
      context: backend
    environment:
      - PORT=${API_PORT}
      - FLASK_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
  web:
    image: web:prod
    depends_on:
      - api
    build:
      context: frontend
      target: production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_HOST=http://localhost:3000
    ports:
      - ${WEB_PORT}:3000
    expose:
      - ${WEB_PORT}
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    expose:
      - 5432
    ports:
      - "5432:5432"