version: '3.8'

services:
  api:
    image: api:dev
    depends_on:
      - db
    build:
      context: backend
    environment:
      - FLASK_ENV=development
      - PORT=${PORT}
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    restart: always
    volumes:
      - ./backend/:/app
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    expose:
      - 5432
    ports:
      - "5432:5432"